name: PHP Test

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Php Build & Test
    
    strategy:
      matrix:
        php-version: [7]
        os: [ubuntu-latest]
        es-version: [5.3.2]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: curl
      env:
        COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: |
        composer install --prefer-dist

    - name: Runs Elasticsearch ${{ matrix.es-version }}
      uses: getong/elasticsearch-action@v1.2
      with:
        elasticsearch version: '${{ es-version }}'
        host port: 9200
        container port: 9200
        host node port: 9300
        node port: 9300
        discovery type: 'single-node'

    - name: Run test suite
      run: ./vendor/bin/phpunit --coverage-text
      env:
        ELASTICSEARCH_URL: http://localhost:9200